// AUTO-GENERATED by scripts/gen-teikin-catalog.mjs. Do not edit by hand.
// Источник: teikin.com e-catalog + pdftotext.
// Ручные записи в teikin-catalog.ts ПЕРЕЗАПИСЫВАЮТ авто-данные.

import type { TeikinEntry } from './teikin-catalog';

export const teikinAutoCatalog: Record<string, Partial<TeikinEntry>> = {
  "B3":   {
      "display_name": "Mazda B3",
      "image": "/teikin-catalog/b3.png",
      "teikin_pistons": [
        "42127"
      ],
      "fuel": "GASOLINE",
      "cc": 1323,
      "cyl": 4,
      "bore_mm": 71,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "B3Y0-11-SA0",
        "KK1YO-11-SAO",
        "B315-11-102"
      ]
    },
  "B6 16V":   {
      "display_name": "Mazda B6",
      "image": "/teikin-catalog/b6-16v.png",
      "teikin_pistons": [
        "42171"
      ],
      "fuel": "GASOLINE",
      "cc": 1597,
      "cyl": 4,
      "bore_mm": 78,
      "pin_diameter_mm": 19.98,
      "oem_piston": [
        "B6Y0-11-SA0",
        "B6Y0-11-SA0A",
        "B630-11-102"
      ]
    },
  "B6 8V":   {
      "display_name": "Mazda B6",
      "image": "/teikin-catalog/b6-8v.png",
      "teikin_pistons": [
        "42171"
      ],
      "fuel": "GASOLINE",
      "cc": 1597,
      "cyl": 4,
      "bore_mm": 78,
      "pin_diameter_mm": 19.98,
      "oem_piston": [
        "B6Y0-11-SA0",
        "B6Y0-11-SA0A",
        "B630-11-102"
      ]
    },
  "BP":   {
      "display_name": "Mazda BP-II",
      "image": "/teikin-catalog/bp.png",
      "teikin_pistons": [
        "42200"
      ],
      "fuel": "GASOLINE",
      "cc": 1839,
      "cyl": 4,
      "bore_mm": 83,
      "pin_diameter_mm": 19.985,
      "oem_piston": [
        "BPY0-11-SA0",
        "BPY0-11-SA0A"
      ]
    },
  "BP Dohs":   {
      "display_name": "Mazda BP-II",
      "image": "/teikin-catalog/bp-dohs.png",
      "teikin_pistons": [
        "42200"
      ],
      "fuel": "GASOLINE",
      "cc": 1839,
      "cyl": 4,
      "bore_mm": 83,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "BPZ0-11-SA0"
      ]
    },
  "E3":   {
      "display_name": "Mazda E3",
      "image": "/teikin-catalog/e3.png",
      "teikin_pistons": [
        "42131"
      ],
      "fuel": "GASOLINE",
      "cc": 1296,
      "cyl": 4,
      "bore_mm": 77,
      "pin_diameter_mm": 19.98,
      "oem_piston": [
        "E302-23-200/A",
        "E302-11-102A"
      ]
    },
  "F2 12V":   {
      "display_name": "Mazda F2",
      "image": "/teikin-catalog/f2-12v.png",
      "teikin_pistons": [
        "42164"
      ],
      "fuel": "GASOLINE",
      "cc": 2184,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 21.98,
      "oem_piston": [
        "F2Y4-11-SAO",
        "F2Y2-1"
      ]
    },
  "F6":   {
      "display_name": "Mazda F6",
      "image": "/teikin-catalog/f6.png",
      "teikin_pistons": [
        "42159"
      ],
      "fuel": "GASOLINE",
      "cc": 1587,
      "cyl": 4,
      "bore_mm": 81,
      "pin_diameter_mm": 21.98,
      "oem_piston": [
        "F605-23-200",
        "F601-2",
        "F6Y1-11",
        "F6Y1-11"
      ]
    },
  "FE 8V / F8":   {
      "display_name": "Mazda FE",
      "image": "/teikin-catalog/fe-8v-f8.png",
      "teikin_pistons": [
        "42157"
      ],
      "fuel": "GASOLINE",
      "cc": 2000,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 21.98,
      "oem_piston": [
        "FE01-23-200",
        "FE01-11-102",
        "FE01-23-210",
        "FE01-23-220"
      ]
    },
  "FE DOHC":   {
      "display_name": "Mazda FE",
      "image": "/teikin-catalog/fe-dohc.png",
      "teikin_pistons": [
        "42157"
      ],
      "fuel": "GASOLINE",
      "cc": 2000,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 21.98,
      "oem_piston": [
        "FE01-23-200",
        "FE01-11-102",
        "FE01-23-210",
        "FE01-23-220"
      ]
    },
  "FS/FP":   {
      "display_name": "Mazda FS",
      "image": "/teikin-catalog/fs-fp.png",
      "teikin_pistons": [
        "42166"
      ],
      "fuel": "GASOLINE",
      "cc": 1991,
      "cyl": 4,
      "bore_mm": 83,
      "pin_diameter_mm": 19,
      "oem_piston": [
        "FSY1-11-SA0",
        "FP01-11-102A"
      ]
    },
  "GY":   {
      "display_name": "Mazda GY",
      "image": "/teikin-catalog/gy.png",
      "teikin_pistons": [
        "42199"
      ],
      "fuel": "GASOLINE",
      "cc": 2498,
      "cyl": 6,
      "bore_mm": 81.65,
      "pin_diameter_mm": 21.015,
      "oem_piston": [
        "GY01-11-100C",
        "1U2ZZ6100AA"
      ]
    },
  "KF":   {
      "display_name": "Mazda KF",
      "image": "/teikin-catalog/kf.png",
      "teikin_pistons": [
        "42665"
      ],
      "fuel": "GASOLINE",
      "cc": 1995,
      "cyl": 6,
      "bore_mm": 78,
      "pin_diameter_mm": 18.98
    },
  "KL":   {
      "display_name": "Mazda KL",
      "image": "/teikin-catalog/kl.png",
      "teikin_pistons": [
        "42664"
      ],
      "fuel": "GASOLINE",
      "cc": 2496,
      "cyl": 6,
      "bore_mm": 84.5,
      "pin_diameter_mm": 19.99
    },
  "L3":   {
      "display_name": "Mazda L3",
      "image": "/teikin-catalog/l3.png",
      "teikin_pistons": [
        "42205"
      ],
      "fuel": "GASOLINE",
      "cc": 2300,
      "cyl": 4,
      "bore_mm": 87.5,
      "pin_diameter_mm": 21,
      "oem_piston": [
        "L3Y5-11-010",
        "L3Y9-11-010",
        "LFY1-11",
        "LFY5-1"
      ]
    },
  "L3-T I":   {
      "display_name": "Mazda L3",
      "image": "/teikin-catalog/l3-t-i.png",
      "teikin_pistons": [
        "42205"
      ],
      "fuel": "GASOLINE",
      "cc": 2300,
      "cyl": 4,
      "bore_mm": 87.5,
      "pin_diameter_mm": 21,
      "oem_piston": [
        "L3Y5-11-010",
        "L3Y9-11-010",
        "LFY1-11",
        "LFY5-1"
      ]
    },
  "LF":   {
      "display_name": "Mazda LF",
      "image": "/teikin-catalog/lf.png",
      "teikin_pistons": [
        "42210"
      ],
      "fuel": "GASOLINE",
      "cc": 2000,
      "cyl": 4,
      "bore_mm": 87.5,
      "pin_diameter_mm": 21,
      "oem_piston": [
        "LFY2-11-010",
        "L3Y3-1",
        "LFY1-11",
        "LFY5-1"
      ]
    },
  "R2 II":   {
      "display_name": "Mazda R2",
      "image": "/teikin-catalog/r2-ii.png",
      "teikin_pistons": [
        "42167",
        "42167A"
      ],
      "fuel": "DIESEL",
      "cc": 2184,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 25,
      "oem_piston": [
        "RF01-23-200",
        "K7YO-11-SAO",
        "RF01-23-200B"
      ]
    },
  "RF/R2":   {
      "display_name": "Mazda RF",
      "image": "/teikin-catalog/rf-r2.png",
      "teikin_pistons": [
        "42610AG"
      ],
      "fuel": "DIESEL",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 30,
      "oem_piston": [
        "RFY4-11-SA0A",
        "RFY2-11-SC0"
      ]
    },
  "RF7 16V":   {
      "display_name": "Mazda RF7",
      "image": "/teikin-catalog/rf7-16v.png",
      "teikin_pistons": [
        "42675AG"
      ],
      "fuel": "DIESEL",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 30,
      "oem_piston": [
        "REY7-11-SBOA"
      ]
    },
  "UC":   {
      "display_name": "Mazda UC",
      "image": "/teikin-catalog/uc.png",
      "teikin_pistons": [
        "42600"
      ],
      "fuel": "GASOLINE",
      "cc": 1415,
      "cyl": 4,
      "bore_mm": 77,
      "pin_diameter_mm": 19.99,
      "oem_piston": [
        "8569-23-200",
        "8569-23"
      ]
    },
  "WL":   {
      "display_name": "Mazda WL-T",
      "image": "/teikin-catalog/wl.png",
      "teikin_pistons": [
        "42185",
        "42185A",
        "42185AG"
      ],
      "fuel": "DIESEL",
      "cc": 2500,
      "cyl": 4,
      "bore_mm": 93,
      "pin_diameter_mm": 32,
      "oem_piston": [
        "WLY3-11-SAOC",
        "WLY5-11-SAOB"
      ]
    },
  "WL Turbo":   {
      "display_name": "Mazda WL-T",
      "image": "/teikin-catalog/wl-turbo.png",
      "teikin_pistons": [
        "42185",
        "42185A",
        "42185AG"
      ],
      "fuel": "DIESEL",
      "cc": 2499,
      "cyl": 4,
      "bore_mm": 93,
      "pin_diameter_mm": 32,
      "oem_piston": [
        "WLY8-11-SAOB",
        "WLY1-11-SAOA",
        "W5Y8-11-SAOD"
      ]
    },
  "Z5 Dohs":   {
      "display_name": "Mazda Z5",
      "image": "/teikin-catalog/z5-dohs.png",
      "teikin_pistons": [
        "42173"
      ],
      "fuel": "GASOLINE",
      "cc": 1489,
      "cyl": 4,
      "bore_mm": 75.3,
      "pin_diameter_mm": 19.98,
      "oem_piston": [
        "Z5YO-11-SAO",
        "Z5Y0-11-SA0B"
      ]
    },
  "ZL":   {
      "display_name": "Mazda ZL-VE",
      "image": "/teikin-catalog/zl.png",
      "teikin_pistons": [
        "42672"
      ],
      "fuel": "GASOLINE",
      "cc": 1498,
      "cyl": 4,
      "bore_mm": 78,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "ZLY2-11-SAO",
        "ZLY2-11-SBO",
        "ZLY2-11-SBX"
      ]
    },
  "4A31":   {
      "display_name": "Mitsubishi 4A31",
      "image": "/teikin-catalog/4a31.png",
      "teikin_pistons": [
        "43680"
      ],
      "fuel": "GASOLINE",
      "cyl": 4,
      "pin_diameter_mm": 16,
      "oem_piston": [
        "MD333030",
        "MD333031",
        "MD333032",
        "MD333033"
      ]
    },
  "4A91":   {
      "display_name": "Mitsubishi 4A91 MIVEC",
      "image": "/teikin-catalog/4a91.png",
      "teikin_pistons": [
        "43303"
      ],
      "fuel": "GASOLINE",
      "cc": 1499,
      "cyl": 4,
      "bore_mm": 75,
      "pin_diameter_mm": 18.01,
      "oem_piston": [
        "MN195611",
        "MN19565"
      ]
    },
  "4B11/10":   {
      "display_name": "Mitsubishi 4B11",
      "image": "/teikin-catalog/4b11-10.png",
      "teikin_pistons": [
        "43692"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 21,
      "oem_piston": [
        "1110B478",
        "1110B479",
        "1110B480",
        "1110C1"
      ]
    },
  "4B12":   {
      "display_name": "Mitsubishi 4B12",
      "image": "/teikin-catalog/4b12.png",
      "teikin_pistons": [
        "43694"
      ],
      "fuel": "GASOLINE",
      "cc": 2359,
      "cyl": 4,
      "bore_mm": 88,
      "pin_diameter_mm": 21,
      "oem_piston": [
        "1110B365",
        "1110B366",
        "1110B367",
        "1110B483"
      ]
    },
  "4D55 New":   {
      "display_name": "Mitsubishi 4D55 / 4D56",
      "image": "/teikin-catalog/4d55-new.png",
      "teikin_pistons": [
        "43171",
        "43171A"
      ],
      "fuel": "DIESEL",
      "cc": 2346,
      "cyl": 4,
      "bore_mm": 91.1,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "MD050021",
        "MD103318",
        "23410-42000",
        "23410-42010/20"
      ]
    },
  "4D55/56":   {
      "display_name": "Mitsubishi 4D55 / 4D56",
      "image": "/teikin-catalog/4d55-56.png",
      "teikin_pistons": [
        "43171",
        "43171A"
      ],
      "fuel": "DIESEL",
      "cc": 2346,
      "cyl": 4,
      "bore_mm": 91.1,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "MD050021",
        "MD103318",
        "23410-42000",
        "23410-42010/20"
      ]
    },
  "4D55T":   {
      "display_name": "Mitsubishi 4D55T/4D56T-II",
      "image": "/teikin-catalog/4d55t.png",
      "teikin_pistons": [
        "43672AG"
      ],
      "fuel": "DIESEL",
      "cc": 2476,
      "cyl": 4,
      "bore_mm": 91.1,
      "pin_diameter_mm": 32,
      "oem_piston": [
        "MD377962",
        "MD377963",
        "MD377965",
        "MD377966"
      ]
    },
  "4D56 L200":   {
      "display_name": "Mitsubishi 4D55 / 4D56",
      "image": "/teikin-catalog/4d56-l200.png",
      "teikin_pistons": [
        "43171",
        "43171A"
      ],
      "fuel": "DIESEL",
      "cc": 2346,
      "cyl": 4,
      "bore_mm": 91.1,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "MD050021",
        "MD103318",
        "23410-42000",
        "23410-42010/20"
      ]
    },
  "4D56TNew":   {
      "display_name": "Mitsubishi 4D55 / 4D56",
      "image": "/teikin-catalog/4d56tnew.png",
      "teikin_pistons": [
        "43171",
        "43171A"
      ],
      "fuel": "DIESEL",
      "cc": 2346,
      "cyl": 4,
      "bore_mm": 91.1,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "MD050021",
        "MD103318",
        "23410-42000",
        "23410-42010/20"
      ]
    },
  "4D68":   {
      "display_name": "Mitsubishi 4D68",
      "image": "/teikin-catalog/4d68.png",
      "teikin_pistons": [
        "43613",
        "43613A"
      ],
      "fuel": "DIESEL",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 82.7,
      "pin_diameter_mm": 25,
      "oem_piston": [
        "MD194163",
        "MD194168"
      ]
    },
  "4D68T":   {
      "display_name": "Mitsubishi 4D68T",
      "image": "/teikin-catalog/4d68t.png",
      "teikin_pistons": [
        "43612",
        "43612AG"
      ],
      "fuel": "DIESEL",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 82.7,
      "pin_diameter_mm": 25,
      "oem_piston": [
        "MD194157"
      ]
    },
  "4G13":   {
      "display_name": "Mitsubishi 4G13-II",
      "image": "/teikin-catalog/4g13.png",
      "teikin_pistons": [
        "43257"
      ],
      "fuel": "GASOLINE",
      "cc": 1298,
      "cyl": 4,
      "bore_mm": 71,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "MD172036"
      ]
    },
  "4G15 12V II":   {
      "display_name": "Mitsubishi 4G15",
      "image": "/teikin-catalog/4g15-12v-ii.png",
      "teikin_pistons": [
        "43217"
      ],
      "fuel": "GASOLINE",
      "cc": 1468,
      "cyl": 4,
      "bore_mm": 75.5,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "MD320435",
        "MD066396",
        "MD144901",
        "MD143914"
      ]
    },
  "4G15 8V":   {
      "display_name": "Mitsubishi 4G15",
      "image": "/teikin-catalog/4g15-8v.png",
      "teikin_pistons": [
        "43217"
      ],
      "fuel": "GASOLINE",
      "cc": 1468,
      "cyl": 4,
      "bore_mm": 75.5,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "MD320435",
        "MD066396",
        "MD144901",
        "MD143914"
      ]
    },
  "4G15New":   {
      "display_name": "Mitsubishi 4G15",
      "image": "/teikin-catalog/4g15new.png",
      "teikin_pistons": [
        "43217"
      ],
      "fuel": "GASOLINE",
      "cc": 1468,
      "cyl": 4,
      "bore_mm": 75.5,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "MD320435",
        "MD066396",
        "MD144901",
        "MD143914"
      ]
    },
  "4G18 II":   {
      "display_name": "Mitsubishi 4G18",
      "image": "/teikin-catalog/4g18-ii.png",
      "teikin_pistons": [
        "43281"
      ],
      "fuel": "GASOLINE",
      "cc": 1584,
      "cyl": 4,
      "bore_mm": 76,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "MD366902",
        "MD367775",
        "MD367776",
        "MD367777",
        "MD349812"
      ]
    },
  "4G37":   {
      "display_name": "Mitsubishi 4G37",
      "image": "/teikin-catalog/4g37.png",
      "teikin_pistons": [
        "43219"
      ],
      "fuel": "GASOLINE",
      "cc": 1755,
      "cyl": 4,
      "bore_mm": 80.6,
      "pin_diameter_mm": 19,
      "oem_piston": [
        "MD100416",
        "MD07711",
        "MD10602",
        "MD15401"
      ]
    },
  "4G54":   {
      "display_name": "Mitsubishi 4G54",
      "image": "/teikin-catalog/4g54.png",
      "teikin_pistons": [
        "43153"
      ],
      "fuel": "GASOLINE",
      "cc": 2555,
      "cyl": 4,
      "bore_mm": 91.1,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "MD026921",
        "MD026835",
        "MD026960",
        "MD027140"
      ]
    },
  "4G63  II":   {
      "display_name": "Mitsubishi 4G63 OLD",
      "image": "/teikin-catalog/4g63-ii.png",
      "teikin_pistons": [
        "43155"
      ],
      "fuel": "GASOLINE",
      "cc": 2555,
      "cyl": 4,
      "bore_mm": 85,
      "pin_diameter_mm": 21,
      "oem_piston": [
        "MD041564",
        "MD040591",
        "MD04158",
        "MD10806"
      ]
    },
  "4G63 III":   {
      "display_name": "Mitsubishi 4G63 OLD",
      "image": "/teikin-catalog/4g63-iii.png",
      "teikin_pistons": [
        "43155"
      ],
      "fuel": "GASOLINE",
      "cc": 2555,
      "cyl": 4,
      "bore_mm": 85,
      "pin_diameter_mm": 21,
      "oem_piston": [
        "MD041564",
        "MD040591",
        "MD04158",
        "MD10806"
      ]
    },
  "4G63BK":   {
      "display_name": "Mitsubishi 4G63 OLD",
      "image": "/teikin-catalog/4g63bk.png",
      "teikin_pistons": [
        "43155"
      ],
      "fuel": "GASOLINE",
      "cc": 2555,
      "cyl": 4,
      "bore_mm": 85,
      "pin_diameter_mm": 21,
      "oem_piston": [
        "MD041564",
        "MD040591",
        "MD04158",
        "MD10806"
      ]
    },
  "4G63K":   {
      "display_name": "Mitsubishi 4G63K",
      "image": "/teikin-catalog/4g63k.png",
      "teikin_pistons": [
        "43261"
      ],
      "fuel": "GASOLINE",
      "cc": 1997,
      "cyl": 4,
      "bore_mm": 85,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "MD188289",
        "MD188292",
        "MD19585"
      ]
    },
  "4G63K II":   {
      "display_name": "Mitsubishi 4G63K",
      "image": "/teikin-catalog/4g63k-ii.png",
      "teikin_pistons": [
        "43261"
      ],
      "fuel": "GASOLINE",
      "cc": 1997,
      "cyl": 4,
      "bore_mm": 85,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "MD188289",
        "MD188292",
        "MD19585"
      ]
    },
  "4G69 I":   {
      "display_name": "Mitsubishi 4G69",
      "image": "/teikin-catalog/4g69-i.png",
      "teikin_pistons": [
        "43287"
      ],
      "fuel": "GASOLINE",
      "cc": 2378,
      "cyl": 4,
      "bore_mm": 87,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "MN183396",
        "MN163080"
      ]
    },
  "4G92":   {
      "display_name": "Mitsubishi 4G92S-H",
      "image": "/teikin-catalog/4g92.png",
      "teikin_pistons": [
        "43657"
      ],
      "fuel": "GASOLINE",
      "cc": 1597,
      "cyl": 4,
      "bore_mm": 81,
      "pin_diameter_mm": 19,
      "oem_piston": [
        "MD329140-6",
        "MD13721",
        "MD17718",
        "MD18034"
      ]
    },
  "4G93":   {
      "display_name": "Mitsubishi 4G93",
      "image": "/teikin-catalog/4g93.png",
      "teikin_pistons": [
        "43658"
      ],
      "fuel": "GASOLINE",
      "cc": 1834,
      "cyl": 4,
      "bore_mm": 81,
      "pin_diameter_mm": 19,
      "oem_piston": [
        "MD329139",
        "MD13721",
        "MD17718",
        "MD18034"
      ]
    },
  "4M40":   {
      "display_name": "Mitsubishi 4M40-T",
      "image": "/teikin-catalog/4m40.png",
      "teikin_pistons": [
        "43232",
        "43232A",
        "43232AG"
      ],
      "fuel": "DIESEL",
      "cc": 2835,
      "cyl": 4,
      "bore_mm": 95,
      "pin_diameter_mm": 30,
      "oem_piston": [
        "ME200689",
        "ME200688",
        "ME200690",
        "ME204029",
        "ME204030"
      ]
    },
  "4M40 #2":   {
      "display_name": "Mitsubishi 4M40-T",
      "image": "/teikin-catalog/4m40-2.png",
      "teikin_pistons": [
        "43232",
        "43232A",
        "43232AG"
      ],
      "fuel": "DIESEL",
      "cc": 2835,
      "cyl": 4,
      "bore_mm": 95,
      "pin_diameter_mm": 30,
      "oem_piston": [
        "ME200689",
        "ME200688",
        "ME200690",
        "ME204029",
        "ME204030"
      ]
    },
  "4M40T":   {
      "display_name": "Mitsubishi 4M40-T",
      "image": "/teikin-catalog/4m40t.png",
      "teikin_pistons": [
        "43232",
        "43232A",
        "43232AG"
      ],
      "fuel": "DIESEL",
      "cc": 2835,
      "cyl": 4,
      "bore_mm": 95,
      "pin_diameter_mm": 30,
      "oem_piston": [
        "ME200689",
        "ME200688",
        "ME200690",
        "ME204029",
        "ME204030"
      ]
    },
  "4M41":   {
      "display_name": "Mitsubishi 4M41-T",
      "image": "/teikin-catalog/4m41.png",
      "teikin_pistons": [
        "43663AG"
      ],
      "fuel": "DIESEL",
      "cc": 3200,
      "cyl": 4,
      "bore_mm": 98.5,
      "pin_diameter_mm": 32,
      "oem_piston": [
        "ME191469",
        "ME191470",
        "ME191471",
        "1110C623/4/5"
      ]
    },
  "6A12":   {
      "display_name": "Mitsubishi 6A12",
      "image": "/teikin-catalog/6a12.png",
      "teikin_pistons": [
        "43677"
      ],
      "fuel": "GASOLINE",
      "cc": 1999,
      "cyl": 6,
      "bore_mm": 78.4,
      "pin_diameter_mm": 19
    },
  "6B31":   {
      "display_name": "Mitsubishi 6B31",
      "image": "/teikin-catalog/6b31.png",
      "teikin_pistons": [
        "43297"
      ],
      "fuel": "GASOLINE",
      "cc": 2998,
      "cyl": 6,
      "bore_mm": 87.6,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "1110B629",
        "1110B630",
        "1110B631"
      ]
    },
  "6G72 12V":   {
      "display_name": "Mitsubishi 6G72",
      "image": "/teikin-catalog/6g72-12v.png",
      "teikin_pistons": [
        "43218"
      ],
      "fuel": "GASOLINE",
      "cc": 2972,
      "cyl": 6,
      "bore_mm": 91.1,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "131252/4"
      ]
    },
  "6G74":   {
      "display_name": "Mitsubishi 6G74",
      "image": "/teikin-catalog/6g74.png",
      "teikin_pistons": [
        "43247"
      ],
      "fuel": "GASOLINE",
      "cc": 3496,
      "cyl": 6,
      "bore_mm": 93,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "MD308276",
        "MD189498",
        "23410-35700",
        "23410-35710/20"
      ]
    },
  "6G74 III":   {
      "display_name": "Mitsubishi 6G74-III",
      "image": "/teikin-catalog/6g74-iii.png",
      "teikin_pistons": [
        "43284"
      ],
      "fuel": "GASOLINE",
      "cc": 3500,
      "cyl": 6,
      "bore_mm": 93,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "MN149038",
        "MN149037",
        "MN14039",
        "MD371361",
        "MD371362"
      ]
    },
  "6G75":   {
      "display_name": "Mitsubishi 6G75",
      "image": "/teikin-catalog/6g75.png",
      "teikin_pistons": [
        "43290"
      ],
      "fuel": "GASOLINE",
      "cc": 3828,
      "cyl": 6,
      "bore_mm": 95,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "MN183040"
      ]
    },
  "CA18":   {
      "display_name": "Nissan CA18",
      "image": "/teikin-catalog/ca18.png",
      "teikin_pistons": [
        "44190"
      ],
      "fuel": "GASOLINE",
      "cc": 1809,
      "cyl": 4,
      "bore_mm": 83,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "12010-D0301",
        "12010-D1201",
        "12010-01F01",
        "12010-01F02"
      ]
    },
  "CA20":   {
      "display_name": "Nissan CA20",
      "image": "/teikin-catalog/ca20.png",
      "teikin_pistons": [
        "44193"
      ],
      "fuel": "GASOLINE",
      "cc": 1974,
      "cyl": 4,
      "bore_mm": 84.5,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "12010-04E11",
        "12010-04F01/11",
        "12010-10F01"
      ]
    },
  "CD20":   {
      "display_name": "Nissan CD20",
      "image": "/teikin-catalog/cd20.png",
      "teikin_pistons": [
        "44602",
        "44602A"
      ],
      "fuel": "DIESEL",
      "cc": 1973,
      "cyl": 4,
      "bore_mm": 84.5,
      "pin_diameter_mm": 25,
      "oem_piston": [
        "A2010-57J01",
        "12010-57J00",
        "A2010-8E100",
        "12010-57J01/2/3/4",
        "A2010-57J11/2/3/4"
      ]
    },
  "CD20T NEW":   {
      "display_name": "Nissan CD20-T",
      "image": "/teikin-catalog/cd20t-new.png",
      "teikin_pistons": [
        "44681AG"
      ],
      "fuel": "DIESEL",
      "cc": 1973,
      "cyl": 4,
      "bore_mm": 84.5,
      "pin_diameter_mm": 28,
      "oem_piston": [
        "10-1C310",
        "0-2J671/2"
      ]
    },
  "E13/15":   {
      "display_name": "Nissan E13",
      "image": "/teikin-catalog/e13-15.png",
      "teikin_pistons": [
        "44611"
      ],
      "fuel": "GASOLINE",
      "cc": 1270,
      "cyl": 4,
      "bore_mm": 76,
      "pin_diameter_mm": 19,
      "oem_piston": [
        "12010-01M02",
        "12010-01M12",
        "12010-01M00",
        "12010-01M22"
      ]
    },
  "GA14DS":   {
      "display_name": "Nissan GA14DS",
      "image": "/teikin-catalog/ga14ds.png",
      "teikin_pistons": [
        "44614"
      ],
      "fuel": "GASOLINE",
      "cc": 1392,
      "cyl": 4,
      "bore_mm": 73.6,
      "pin_diameter_mm": 19,
      "oem_piston": [
        "12010-87A61"
      ]
    },
  "GA15DS":   {
      "display_name": "Nissan GA15DS-II",
      "image": "/teikin-catalog/ga15ds.png",
      "teikin_pistons": [
        "44337"
      ],
      "fuel": "GASOLINE",
      "cc": 1497,
      "cyl": 4,
      "bore_mm": 73.6,
      "pin_diameter_mm": 19,
      "oem_piston": [
        "A2010-53Y00",
        "A2010-53Y01"
      ]
    },
  "GA16DE":   {
      "display_name": "Nissan GA16DE",
      "image": "/teikin-catalog/ga16de.png",
      "teikin_pistons": [
        "44260"
      ],
      "fuel": "GASOLINE",
      "cc": 1597,
      "cyl": 4,
      "bore_mm": 76,
      "pin_diameter_mm": 19,
      "oem_piston": [
        "A2010-74Y10",
        "A2010-57Y00"
      ]
    },
  "KA24DE":   {
      "display_name": "Nissan KA24DE",
      "image": "/teikin-catalog/ka24de.png",
      "teikin_pistons": [
        "44321"
      ],
      "fuel": "GASOLINE",
      "cc": 2389,
      "cyl": 4,
      "bore_mm": 89,
      "pin_diameter_mm": 20.98,
      "oem_piston": [
        "A2010-53F00",
        "A2010-1E400"
      ]
    },
  "KA24E II":   {
      "display_name": "Nissan KA24E",
      "image": "/teikin-catalog/ka24e-ii.png",
      "teikin_pistons": [
        "44271"
      ],
      "fuel": "GASOLINE",
      "cc": 2388,
      "cyl": 4,
      "bore_mm": 89,
      "pin_diameter_mm": 21,
      "oem_piston": [
        "12010-86G20"
      ]
    },
  "LD20":   {
      "display_name": "Nissan LD20",
      "image": "/teikin-catalog/ld20.png",
      "teikin_pistons": [
        "44176",
        "44176A"
      ],
      "fuel": "DIESEL",
      "cc": 1952,
      "cyl": 4,
      "bore_mm": 85,
      "pin_diameter_mm": 25,
      "oem_piston": [
        "12010-18L02",
        "12010-W1762",
        "12010-W1702"
      ]
    },
  "MR20DE":   {
      "display_name": "Nissan MR20DE",
      "image": "/teikin-catalog/mr20de.png",
      "teikin_pistons": [
        "44350"
      ],
      "fuel": "GASOLINE",
      "cc": 1997,
      "cyl": 4,
      "bore_mm": 84,
      "pin_diameter_mm": 19.99,
      "oem_piston": [
        "A2010-EN210",
        "A2010-EN20B",
        "12010-ET000",
        "A2010-ET000",
        "A2010-ET001"
      ]
    },
  "QD32":   {
      "display_name": "Nissan QD32",
      "image": "/teikin-catalog/qd32.png",
      "teikin_pistons": [
        "44297",
        "44297A",
        "44297A"
      ],
      "fuel": "DIESEL",
      "cc": 3153,
      "cyl": 4,
      "bore_mm": 99.2,
      "pin_diameter_mm": 33,
      "oem_piston": [
        "12010-2S605"
      ]
    },
  "QG18DE-II":   {
      "display_name": "Nissan QG18DE-II",
      "image": "/teikin-catalog/qg18de-ii.png",
      "teikin_pistons": [
        "44333"
      ],
      "fuel": "GASOLINE",
      "cc": 1809,
      "cyl": 4,
      "bore_mm": 80,
      "pin_diameter_mm": 18.99,
      "oem_piston": [
        "12010-F4670",
        "010-AU300/1/2",
        "010-AU300/1/2/71/72",
        "12014/15-AU300",
        "A2010-F4671"
      ]
    },
  "QR20":   {
      "display_name": "Nissan QR20DE",
      "image": "/teikin-catalog/qr20.png",
      "teikin_pistons": [
        "44342"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 89,
      "pin_diameter_mm": 19.99,
      "oem_piston": [
        "A2010-8H502",
        "A2010-8H501",
        "A2010-8H571",
        "A2010-8H311/2",
        "A2010-8H376"
      ]
    },
  "QR25 I":   {
      "display_name": "Nissan QR25DE",
      "image": "/teikin-catalog/qr25-i.png",
      "teikin_pistons": [
        "44328"
      ],
      "fuel": "GASOLINE",
      "cc": 2488,
      "cyl": 4,
      "bore_mm": 89,
      "pin_diameter_mm": 19.99,
      "oem_piston": [
        "A2010-9H576",
        "A2010-9H511",
        "A2010-9H512",
        "A2010-8J011",
        "A2010-8J012"
      ]
    },
  "QR25 II":   {
      "display_name": "Nissan QR25DE",
      "image": "/teikin-catalog/qr25-ii.png",
      "teikin_pistons": [
        "44328"
      ],
      "fuel": "GASOLINE",
      "cc": 2488,
      "cyl": 4,
      "bore_mm": 89,
      "pin_diameter_mm": 19.99,
      "oem_piston": [
        "A2010-9H576",
        "A2010-9H511",
        "A2010-9H512",
        "A2010-8J011",
        "A2010-8J012"
      ]
    },
  "RD28":   {
      "display_name": "Nissan RD28",
      "image": "/teikin-catalog/rd28.png",
      "teikin_pistons": [
        "44606"
      ],
      "fuel": "DIESEL",
      "cc": 2825,
      "cyl": 6,
      "bore_mm": 85,
      "pin_diameter_mm": 25,
      "oem_piston": [
        "12010-V7213",
        "A2010-V7213"
      ]
    },
  "RD28T":   {
      "display_name": "Nissan RD28-T",
      "image": "/teikin-catalog/rd28t.png",
      "teikin_pistons": [
        "44623AG"
      ],
      "fuel": "DIESEL",
      "cc": 2825,
      "cyl": 6,
      "bore_mm": 85,
      "pin_diameter_mm": 27,
      "oem_piston": [
        "12010-22J11",
        "12010-22J62",
        "12010-22J64"
      ]
    },
  "RD28T New":   {
      "display_name": "Nissan RD28-T",
      "image": "/teikin-catalog/rd28t-new.png",
      "teikin_pistons": [
        "44623AG"
      ],
      "fuel": "DIESEL",
      "cc": 2825,
      "cyl": 6,
      "bore_mm": 85,
      "pin_diameter_mm": 27,
      "oem_piston": [
        "12010-22J11",
        "12010-22J62",
        "12010-22J64"
      ]
    },
  "SR20":   {
      "display_name": "Nissan SR20DE",
      "image": "/teikin-catalog/sr20.png",
      "teikin_pistons": [
        "44601"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "A2010-65J02",
        "A2010-65J01",
        "12033-6",
        "12035-5"
      ]
    },
  "TD27":   {
      "display_name": "Nissan TD27",
      "image": "/teikin-catalog/td27.png",
      "teikin_pistons": [
        "44267",
        "44267A"
      ],
      "fuel": "DIESEL",
      "cc": 2663,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 28,
      "oem_piston": [
        "12010-10T02",
        "12010-10T12",
        "12010-43G02",
        "12010-43G12"
      ]
    },
  "TD27T":   {
      "display_name": "Nissan TD27-T - II",
      "image": "/teikin-catalog/td27t.png",
      "teikin_pistons": [
        "44296",
        "44296A",
        "44296AG",
        "44296AG"
      ],
      "fuel": "DIESEL",
      "cc": 2663,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 30,
      "oem_piston": [
        "12010-7F406",
        "A2010-7F406",
        "A2010-7F407",
        "A2010-7F408"
      ]
    },
  "TD27T III":   {
      "display_name": "Nissan TD27-T - II",
      "image": "/teikin-catalog/td27t-iii.png",
      "teikin_pistons": [
        "44296",
        "44296A",
        "44296AG",
        "44296AG"
      ],
      "fuel": "DIESEL",
      "cc": 2663,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 30,
      "oem_piston": [
        "12010-7F406",
        "A2010-7F406",
        "A2010-7F407",
        "A2010-7F408"
      ]
    },
  "TD27T IV":   {
      "display_name": "Nissan TD27-T - II",
      "image": "/teikin-catalog/td27t-iv.png",
      "teikin_pistons": [
        "44296",
        "44296A",
        "44296AG",
        "44296AG"
      ],
      "fuel": "DIESEL",
      "cc": 2663,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 30,
      "oem_piston": [
        "12010-7F406",
        "A2010-7F406",
        "A2010-7F407",
        "A2010-7F408"
      ]
    },
  "VK56 DE":   {
      "display_name": "Nissan VK56VD",
      "image": "/teikin-catalog/vk56-de.png",
      "teikin_pistons": [
        "44366"
      ],
      "fuel": "GASOLINE",
      "cc": 5552,
      "cyl": 8,
      "bore_mm": 98,
      "pin_diameter_mm": 21.99
    },
  "VQ20":   {
      "display_name": "Nissan VQ20",
      "image": "/teikin-catalog/vq20.png",
      "teikin_pistons": [
        "44689"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 6,
      "bore_mm": 76,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "12010-31U60",
        "A2010-31U60"
      ]
    },
  "VQ30 I":   {
      "display_name": "Nissan VQ30DE",
      "image": "/teikin-catalog/vq30-i.png",
      "teikin_pistons": [
        "44273"
      ],
      "fuel": "GASOLINE",
      "cc": 2960,
      "cyl": 6,
      "bore_mm": 93,
      "pin_diameter_mm": 21.99,
      "oem_piston": [
        "A2010-39U00",
        "A2010-38U10",
        "A2010-38U71"
      ]
    },
  "VQ30 II":   {
      "display_name": "Nissan VQ30DE",
      "image": "/teikin-catalog/vq30-ii.png",
      "teikin_pistons": [
        "44273"
      ],
      "fuel": "GASOLINE",
      "cc": 2960,
      "cyl": 6,
      "bore_mm": 93,
      "pin_diameter_mm": 21.99,
      "oem_piston": [
        "A2010-39U00",
        "A2010-38U10",
        "A2010-38U71"
      ]
    },
  "VQ35":   {
      "display_name": "Nissan VQ35DE-II",
      "image": "/teikin-catalog/vq35.png",
      "teikin_pistons": [
        "44331"
      ],
      "fuel": "GASOLINE",
      "cc": 3498,
      "cyl": 6,
      "bore_mm": 95.5,
      "pin_diameter_mm": 21.99,
      "oem_piston": [
        "A2010-8J101"
      ]
    },
  "VQ35 II":   {
      "display_name": "Nissan VQ35DE-II",
      "image": "/teikin-catalog/vq35-ii.png",
      "teikin_pistons": [
        "44331"
      ],
      "fuel": "GASOLINE",
      "cc": 3498,
      "cyl": 6,
      "bore_mm": 95.5,
      "pin_diameter_mm": 21.99,
      "oem_piston": [
        "A2010-8J101"
      ]
    },
  "VQ40":   {
      "display_name": "Nissan VQ40DE",
      "image": "/teikin-catalog/vq40.png",
      "teikin_pistons": [
        "44341"
      ],
      "fuel": "GASOLINE",
      "cc": 3954,
      "cyl": 6,
      "bore_mm": 95.5,
      "pin_diameter_mm": 21.99,
      "oem_piston": [
        "12010-EA200"
      ]
    },
  "ZD30 = TD27 III 34137":   {
      "display_name": "Nissan ZD30",
      "image": "/teikin-catalog/zd30-td27-iii-34137.png",
      "teikin_pistons": [
        "44672AG"
      ],
      "fuel": "DIESEL",
      "cc": 2953,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 33,
      "oem_piston": [
        "12010-VC112",
        "12010-VC111",
        "12010-VC101",
        "12010-VC102"
      ]
    },
  "1A/3A":   {
      "display_name": "Toyota 1A",
      "image": "/teikin-catalog/1a-3a.png",
      "teikin_pistons": [
        "46658"
      ],
      "fuel": "GASOLINE",
      "cc": 1452,
      "cyl": 4,
      "bore_mm": 77.5,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-15010"
      ]
    },
  "1AD":   {
      "display_name": "Toyota 1AD-FTV",
      "image": "/teikin-catalog/1ad.png",
      "teikin_pistons": [
        "46678AG"
      ],
      "fuel": "DIESEL",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "13101-0R030",
        "13101-0R032"
      ]
    },
  "1AR":   {
      "display_name": "Toyota 1AR-FE",
      "image": "/teikin-catalog/1ar.png",
      "teikin_pistons": [
        "46697"
      ],
      "fuel": "GASOLINE",
      "cc": 2672,
      "cyl": 4,
      "bore_mm": 90,
      "pin_diameter_mm": 22
    },
  "1AZ":   {
      "display_name": "Toyota 1AZ-FSE",
      "image": "/teikin-catalog/1az.png",
      "teikin_pistons": [
        "46365"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13211-28040-B0"
      ]
    },
  "1AZ FSE":   {
      "display_name": "Toyota 1AZ-FSE",
      "image": "/teikin-catalog/1az-fse.png",
      "teikin_pistons": [
        "46365"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13211-28040-B0"
      ]
    },
  "1AZ II":   {
      "display_name": "Toyota 1AZ-FSE",
      "image": "/teikin-catalog/1az-ii.png",
      "teikin_pistons": [
        "46365"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13211-28040-B0"
      ]
    },
  "1C":   {
      "display_name": "Toyota 1C",
      "image": "/teikin-catalog/1c.png",
      "teikin_pistons": [
        "46112"
      ],
      "fuel": "DIESEL",
      "cc": 1839,
      "cyl": 4,
      "bore_mm": 83,
      "pin_diameter_mm": 27,
      "oem_piston": [
        "13101-64010",
        "13101-64020"
      ]
    },
  "1CD":   {
      "display_name": "Toyota 1CD-FTV",
      "image": "/teikin-catalog/1cd.png",
      "teikin_pistons": [
        "46680AG"
      ],
      "fuel": "DIESEL",
      "cc": 1995,
      "cyl": 4,
      "bore_mm": 82.2,
      "pin_diameter_mm": 31,
      "oem_piston": [
        "13101-OG010",
        "13101-OG0A0",
        "13101-OG0B0",
        "13101-OG0C0"
      ]
    },
  "1FZ 100":   {
      "display_name": "Toyota 1FZ-FE",
      "image": "/teikin-catalog/1fz-100.png",
      "teikin_pistons": [
        "46270"
      ],
      "fuel": "GASOLINE",
      "cc": 4476,
      "cyl": 6,
      "bore_mm": 100,
      "pin_diameter_mm": 26,
      "oem_piston": [
        "13101-66020"
      ]
    },
  "1FZ 80":   {
      "display_name": "Toyota 1FZ-FE",
      "image": "/teikin-catalog/1fz-80.png",
      "teikin_pistons": [
        "46270"
      ],
      "fuel": "GASOLINE",
      "cc": 4476,
      "cyl": 6,
      "bore_mm": 100,
      "pin_diameter_mm": 26,
      "oem_piston": [
        "13101-66020"
      ]
    },
  "1FZ 80 (2)":   {
      "display_name": "Toyota 1FZ-FE",
      "image": "/teikin-catalog/1fz-80-2.png",
      "teikin_pistons": [
        "46270"
      ],
      "fuel": "GASOLINE",
      "cc": 4476,
      "cyl": 6,
      "bore_mm": 100,
      "pin_diameter_mm": 26,
      "oem_piston": [
        "13101-66020"
      ]
    },
  "1GFE II":   {
      "display_name": "Toyota 1G-FE",
      "image": "/teikin-catalog/1gfe-ii.png",
      "teikin_pistons": [
        "46377"
      ],
      "fuel": "GASOLINE",
      "cyl": 6,
      "pin_diameter_mm": 20.012,
      "oem_piston": [
        "13101-70120"
      ]
    },
  "1GR":   {
      "display_name": "Toyota 1GR-FE",
      "image": "/teikin-catalog/1gr.png",
      "teikin_pistons": [
        "46368"
      ],
      "fuel": "GASOLINE",
      "cc": 4000,
      "cyl": 6,
      "bore_mm": 94,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-31030"
      ]
    },
  "1GR 150/200":   {
      "display_name": "Toyota 1GR-FE",
      "image": "/teikin-catalog/1gr-150-200.png",
      "teikin_pistons": [
        "46368"
      ],
      "fuel": "GASOLINE",
      "cc": 4000,
      "cyl": 6,
      "bore_mm": 94,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-31030"
      ]
    },
  "1HD":   {
      "display_name": "Toyota 1HD-T LATE",
      "image": "/teikin-catalog/1hd.png",
      "teikin_pistons": [
        "46268",
        "46268A"
      ],
      "fuel": "DIESEL",
      "cc": 4163,
      "cyl": 6,
      "bore_mm": 94,
      "pin_diameter_mm": 33.01,
      "oem_piston": [
        "13101-17040"
      ]
    },
  "1HDFTE":   {
      "display_name": "Toyota 1HD-FTE",
      "image": "/teikin-catalog/1hdfte.png",
      "teikin_pistons": [
        "46674AG"
      ],
      "fuel": "DIESEL",
      "cc": 4164,
      "cyl": 6,
      "bore_mm": 94,
      "pin_diameter_mm": 33,
      "oem_piston": [
        "13101-17110",
        "13103-17110"
      ]
    },
  "1HZ 80":   {
      "display_name": "Toyota 1HZ, 1PZ",
      "image": "/teikin-catalog/1hz-80.png",
      "teikin_pistons": [
        "46257",
        "46257A"
      ],
      "fuel": "DIESEL",
      "cc": 4163,
      "cyl": 6,
      "bore_mm": 94,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "13101-17010",
        "13101-17100"
      ]
    },
  "1KD I":   {
      "display_name": "Toyota 1KD-FTV",
      "image": "/teikin-catalog/1kd-i.png",
      "teikin_pistons": [
        "46675AG"
      ],
      "fuel": "DIESEL",
      "cc": 2982,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 34,
      "oem_piston": [
        "13101-30020",
        "13103-30020",
        "13104-30020",
        "13105-30020"
      ]
    },
  "1KD II":   {
      "display_name": "Toyota 1KD-FTV",
      "image": "/teikin-catalog/1kd-ii.png",
      "teikin_pistons": [
        "46675AG"
      ],
      "fuel": "DIESEL",
      "cc": 2982,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 34,
      "oem_piston": [
        "13101-30020",
        "13103-30020",
        "13104-30020",
        "13105-30020"
      ]
    },
  "1KR":   {
      "display_name": "Toyota 1KR-FE",
      "image": "/teikin-catalog/1kr.png",
      "teikin_pistons": [
        "46677"
      ],
      "fuel": "GASOLINE",
      "cc": 998,
      "cyl": 3,
      "bore_mm": 71,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-40020",
        "13101-40021"
      ]
    },
  "1KZ":   {
      "display_name": "Toyota 1KZ-TE, 1KZ",
      "image": "/teikin-catalog/1kz.png",
      "teikin_pistons": [
        "46283",
        "46283A",
        "46283AG",
        "46283G"
      ],
      "fuel": "DIESEL",
      "cc": 2982,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 34,
      "oem_piston": [
        "13101-67030"
      ]
    },
  "1KZ NEW":   {
      "display_name": "Toyota 1KZ-TE, 1KZ",
      "image": "/teikin-catalog/1kz-new.png",
      "teikin_pistons": [
        "46283",
        "46283A",
        "46283AG",
        "46283G"
      ],
      "fuel": "DIESEL",
      "cc": 2982,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 34,
      "oem_piston": [
        "13101-67030"
      ]
    },
  "1MZ":   {
      "display_name": "Toyota 1MZFE",
      "image": "/teikin-catalog/1mz.png",
      "teikin_pistons": [
        "46288"
      ],
      "fuel": "GASOLINE",
      "cc": 2995,
      "cyl": 6,
      "bore_mm": 87.5,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "3101-20030 (R)",
        "3101-20020 (L)",
        "3101-20010 (R)",
        "3301-20010 (L)"
      ]
    },
  "1NRFE I":   {
      "display_name": "Toyota 1NR-FE",
      "image": "/teikin-catalog/1nrfe-i.png",
      "teikin_pistons": [
        "46702"
      ],
      "fuel": "GASOLINE",
      "cc": 1329,
      "cyl": 4,
      "bore_mm": 72.5,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-47020"
      ]
    },
  "1NZ":   {
      "display_name": "Toyota 1NZ-FXE",
      "image": "/teikin-catalog/1nz.png",
      "teikin_pistons": [
        "46370"
      ],
      "fuel": "GASOLINE",
      "cc": 1496,
      "cyl": 4,
      "bore_mm": 75,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-21120"
      ]
    },
  "1S":   {
      "display_name": "Toyota 1S",
      "image": "/teikin-catalog/1s.png",
      "teikin_pistons": [
        "46116"
      ],
      "fuel": "GASOLINE",
      "cc": 1832,
      "cyl": 4,
      "bore_mm": 80.5,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "13101-63020",
        "13101-63010",
        "13101-63011"
      ]
    },
  "1SZ":   {
      "display_name": "Toyota 1SZFE",
      "image": "/teikin-catalog/1sz.png",
      "teikin_pistons": [
        "46341"
      ],
      "fuel": "GASOLINE",
      "cc": 998,
      "cyl": 4,
      "bore_mm": 69,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-0J010"
      ]
    },
  "1UR":   {
      "display_name": "Toyota 1UR-FE",
      "image": "/teikin-catalog/1ur.png",
      "teikin_pistons": [
        "46399"
      ],
      "fuel": "GASOLINE",
      "cc": 4608,
      "cyl": 8,
      "bore_mm": 94,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-0S020"
      ]
    },
  "1VD":   {
      "display_name": "Toyota 1VD-FTV",
      "image": "/teikin-catalog/1vd.png",
      "teikin_pistons": [
        "46691AG"
      ],
      "fuel": "DIESEL",
      "cc": 4461,
      "cyl": 8,
      "bore_mm": 86,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "3101-0W020 ( R/L )",
        "13301-0W010"
      ]
    },
  "1ZR":   {
      "display_name": "Toyota 1ZR-FE",
      "image": "/teikin-catalog/1zr.png",
      "teikin_pistons": [
        "46382"
      ],
      "fuel": "GASOLINE",
      "cc": 1598,
      "cyl": 4,
      "bore_mm": 80.5,
      "pin_diameter_mm": 20.012,
      "oem_piston": [
        "13101-37081"
      ]
    },
  "1ZZ":   {
      "display_name": "Toyota 1ZZFE",
      "image": "/teikin-catalog/1zz.png",
      "teikin_pistons": [
        "46334"
      ],
      "fuel": "GASOLINE",
      "cc": 1794,
      "cyl": 4,
      "bore_mm": 79,
      "pin_diameter_mm": 20.012,
      "oem_piston": [
        "13101-22140",
        "13101-22020",
        "13101-22030",
        "13101-22031/60",
        "13101-22142"
      ]
    },
  "2A":   {
      "display_name": "Toyota 2A",
      "image": "/teikin-catalog/2a.png",
      "teikin_pistons": [
        "46604"
      ],
      "fuel": "GASOLINE",
      "cc": 1295,
      "cyl": 4,
      "bore_mm": 76,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-14020"
      ]
    },
  "2AD":   {
      "display_name": "Toyota 2AD-FHV",
      "image": "/teikin-catalog/2ad.png",
      "teikin_pistons": [
        "46679AG"
      ],
      "fuel": "DIESEL",
      "cc": 2231,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "3101-0R020/1/2"
      ]
    },
  "2AR":   {
      "display_name": "Toyota 2AR-FXE",
      "image": "/teikin-catalog/2ar.png",
      "teikin_pistons": [
        "46400"
      ],
      "fuel": "GASOLINE",
      "cc": 2494,
      "cyl": 4,
      "bore_mm": 90,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13211-36060-B0"
      ]
    },
  "2AZ":   {
      "display_name": "Toyota 2AZFE",
      "image": "/teikin-catalog/2az.png",
      "teikin_pistons": [
        "46343"
      ],
      "fuel": "GASOLINE",
      "cc": 2362,
      "cyl": 4,
      "bore_mm": 88.5,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13211-28030",
        "13211-28031"
      ]
    },
  "2AZ 40":   {
      "display_name": "Toyota 2AZFE",
      "image": "/teikin-catalog/2az-40.png",
      "teikin_pistons": [
        "46343"
      ],
      "fuel": "GASOLINE",
      "cc": 2362,
      "cyl": 4,
      "bore_mm": 88.5,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13211-28030",
        "13211-28031"
      ]
    },
  "2C IV":   {
      "display_name": "Toyota 2C",
      "image": "/teikin-catalog/2c-iv.png",
      "teikin_pistons": [
        "46260",
        "46260A"
      ],
      "fuel": "DIESEL",
      "cc": 1974,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 27,
      "oem_piston": [
        "13101-64090"
      ]
    },
  "2C/3C":   {
      "display_name": "Toyota 2C",
      "image": "/teikin-catalog/2c-3c.png",
      "teikin_pistons": [
        "46260",
        "46260A"
      ],
      "fuel": "DIESEL",
      "cc": 1974,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 27,
      "oem_piston": [
        "13101-64090"
      ]
    },
  "2E":   {
      "display_name": "Toyota 2E",
      "image": "/teikin-catalog/2e.png",
      "teikin_pistons": [
        "46141"
      ],
      "fuel": "GASOLINE",
      "cc": 1295,
      "cyl": 4,
      "bore_mm": 73,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-11050",
        "13101-11051"
      ]
    },
  "2GR":   {
      "display_name": "Toyota 2GR-FE",
      "image": "/teikin-catalog/2gr.png",
      "teikin_pistons": [
        "46363",
        "46363-4"
      ],
      "fuel": "GASOLINE",
      "cc": 3456,
      "cyl": 6,
      "bore_mm": 94,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-31091",
        "13101-31090",
        "13101-31092"
      ]
    },
  "2GRFSE":   {
      "display_name": "Toyota 2GR-FSE",
      "image": "/teikin-catalog/2grfse.png",
      "teikin_pistons": [
        "46396"
      ],
      "fuel": "GASOLINE",
      "cc": 3500,
      "cyl": 6,
      "bore_mm": 94,
      "pin_diameter_mm": 22
    },
  "2JZ":   {
      "display_name": "Toyota 2JZGE",
      "image": "/teikin-catalog/2jz.png",
      "teikin_pistons": [
        "46330"
      ],
      "fuel": "GASOLINE",
      "cc": 2997,
      "cyl": 6,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-46030",
        "13101-46031"
      ]
    },
  "2JZ II":   {
      "display_name": "Toyota 2JZGE",
      "image": "/teikin-catalog/2jz-ii.png",
      "teikin_pistons": [
        "46330"
      ],
      "fuel": "GASOLINE",
      "cc": 2997,
      "cyl": 6,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-46030",
        "13101-46031"
      ]
    },
  "2KD":   {
      "display_name": "Toyota 2KD - FTV",
      "image": "/teikin-catalog/2kd.png",
      "teikin_pistons": [
        "46348A",
        "46348AG"
      ],
      "fuel": "DIESEL",
      "cc": 2494,
      "cyl": 4,
      "bore_mm": 92,
      "pin_diameter_mm": 34,
      "oem_piston": [
        "13101-0L020-01",
        "13101-0L022",
        "13101-30030",
        "13101-30031"
      ]
    },
  "2L":   {
      "display_name": "Toyota 2L",
      "image": "/teikin-catalog/2l.png",
      "teikin_pistons": [
        "46240",
        "46240A"
      ],
      "fuel": "DIESEL",
      "cc": 2466,
      "cyl": 4,
      "bore_mm": 92,
      "pin_diameter_mm": 27,
      "oem_piston": [
        "13101-54060"
      ]
    },
  "2L T":   {
      "display_name": "Toyota 2L",
      "image": "/teikin-catalog/2l-t.png",
      "teikin_pistons": [
        "46240",
        "46240A"
      ],
      "fuel": "DIESEL",
      "cc": 2466,
      "cyl": 4,
      "bore_mm": 92,
      "pin_diameter_mm": 27,
      "oem_piston": [
        "13101-54060"
      ]
    },
  "2L T (2)":   {
      "display_name": "Toyota 2L",
      "image": "/teikin-catalog/2l-t-2.png",
      "teikin_pistons": [
        "46240",
        "46240A"
      ],
      "fuel": "DIESEL",
      "cc": 2466,
      "cyl": 4,
      "bore_mm": 92,
      "pin_diameter_mm": 27,
      "oem_piston": [
        "13101-54060"
      ]
    },
  "2NZ II":   {
      "display_name": "Toyota 2NZ-FE",
      "image": "/teikin-catalog/2nz-ii.png",
      "teikin_pistons": [
        "46354"
      ],
      "fuel": "GASOLINE",
      "cc": 1298,
      "cyl": 4,
      "bore_mm": 75,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-21050"
      ]
    },
  "2TR":   {
      "display_name": "Toyota 2TR-FE",
      "image": "/teikin-catalog/2tr.png",
      "teikin_pistons": [
        "46360"
      ],
      "fuel": "GASOLINE",
      "cc": 2700,
      "cyl": 4,
      "bore_mm": 95,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-0C020",
        "13101-75130"
      ]
    },
  "2TZ":   {
      "display_name": "Toyota 2TZ-FE",
      "image": "/teikin-catalog/2tz.png",
      "teikin_pistons": [
        "46313"
      ],
      "fuel": "GASOLINE",
      "cc": 2438,
      "cyl": 4,
      "bore_mm": 95,
      "pin_diameter_mm": 24.007,
      "oem_piston": [
        "13101-76041"
      ]
    },
  "2UZ":   {
      "display_name": "Toyota 2UZFE",
      "image": "/teikin-catalog/2uz.png",
      "teikin_pistons": [
        "46337"
      ],
      "fuel": "GASOLINE",
      "cc": 4663,
      "cyl": 8,
      "bore_mm": 94,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-50050-01(R)",
        "13301-50040-01(L)"
      ]
    },
  "2UZ II":   {
      "display_name": "Toyota 2UZFE",
      "image": "/teikin-catalog/2uz-ii.png",
      "teikin_pistons": [
        "46337"
      ],
      "fuel": "GASOLINE",
      "cc": 4663,
      "cyl": 8,
      "bore_mm": 94,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-50050-01(R)",
        "13301-50040-01(L)"
      ]
    },
  "3C":   {
      "display_name": "Toyota 3C",
      "image": "/teikin-catalog/3c.png",
      "teikin_pistons": [
        "46629A",
        "46629AG",
        "46629G"
      ],
      "fuel": "DIESEL",
      "cc": 2184,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 27,
      "oem_piston": [
        "13101-64150",
        "13101-64151",
        "13101-64210"
      ]
    },
  "3GR":   {
      "display_name": "Toyota 3GR-FE",
      "image": "/teikin-catalog/3gr.png",
      "teikin_pistons": [
        "46386"
      ],
      "fuel": "GASOLINE",
      "cc": 3000,
      "cyl": 6,
      "bore_mm": 87.5,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "3301-31050 (R)",
        "3101-31080 (L)"
      ]
    },
  "3GRFSE":   {
      "display_name": "Toyota 3GR-FSE",
      "image": "/teikin-catalog/3grfse.png",
      "teikin_pistons": [
        "46397"
      ],
      "fuel": "GASOLINE",
      "cc": 3000,
      "cyl": 6,
      "bore_mm": 87.5,
      "pin_diameter_mm": 22
    },
  "3L":   {
      "display_name": "Toyota 3L",
      "image": "/teikin-catalog/3l.png",
      "teikin_pistons": [
        "46256",
        "46256A"
      ],
      "fuel": "DIESEL",
      "cc": 2779,
      "cyl": 4,
      "bore_mm": 96,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "13101-54101",
        "13101-54100"
      ]
    },
  "3MZ":   {
      "display_name": "Toyota 3MZFE",
      "image": "/teikin-catalog/3mz.png",
      "teikin_pistons": [
        "46357"
      ],
      "fuel": "GASOLINE",
      "cc": 3311,
      "cyl": 6,
      "bore_mm": 92,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-0A040",
        "13101-20050"
      ]
    },
  "3NRFE":   {
      "display_name": "Toyota 3NR-FE",
      "image": "/teikin-catalog/3nrfe.png",
      "teikin_pistons": [
        "46387"
      ],
      "fuel": "GASOLINE",
      "cc": 1197,
      "cyl": 4,
      "bore_mm": 72.5,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-0Y030",
        "13101-47051"
      ]
    },
  "3RZ":   {
      "display_name": "Toyota 3RZ-FE, 3RZ-FZ",
      "image": "/teikin-catalog/3rz.png",
      "teikin_pistons": [
        "46312"
      ],
      "fuel": "GASOLINE",
      "cc": 2693,
      "cyl": 4,
      "bore_mm": 95,
      "pin_diameter_mm": 24.007,
      "oem_piston": [
        "13101-75040",
        "13101-75041"
      ]
    },
  "3S":   {
      "display_name": "Toyota 3S-FSE",
      "image": "/teikin-catalog/3s.png",
      "teikin_pistons": [
        "46378"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-74230-01"
      ]
    },
  "3S II":   {
      "display_name": "Toyota 3S-FSE",
      "image": "/teikin-catalog/3s-ii.png",
      "teikin_pistons": [
        "46378"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-74230-01"
      ]
    },
  "3S New":   {
      "display_name": "Toyota 3S-FSE",
      "image": "/teikin-catalog/3s-new.png",
      "teikin_pistons": [
        "46378"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-74230-01"
      ]
    },
  "3SFSE":   {
      "display_name": "Toyota 3S-FSE",
      "image": "/teikin-catalog/3sfse.png",
      "teikin_pistons": [
        "46378"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-74230-01"
      ]
    },
  "3UR":   {
      "display_name": "Toyota 3UR-FE",
      "image": "/teikin-catalog/3ur.png",
      "teikin_pistons": [
        "46388"
      ],
      "fuel": "GASOLINE",
      "cc": 5663,
      "cyl": 8,
      "bore_mm": 94,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-0S011"
      ]
    },
  "3VZ Cam":   {
      "display_name": "Toyota 3VZ-FE",
      "image": "/teikin-catalog/3vz-cam.png",
      "teikin_pistons": [
        "46281"
      ],
      "fuel": "GASOLINE",
      "cc": 2958,
      "cyl": 6,
      "bore_mm": 87.5,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-62040"
      ]
    },
  "3VZ Ran":   {
      "display_name": "Toyota 3VZ-FE",
      "image": "/teikin-catalog/3vz-ran.png",
      "teikin_pistons": [
        "46281"
      ],
      "fuel": "GASOLINE",
      "cc": 2958,
      "cyl": 6,
      "bore_mm": 87.5,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-62040"
      ]
    },
  "3Y":   {
      "display_name": "Toyota 3Y",
      "image": "/teikin-catalog/3y.png",
      "teikin_pistons": [
        "46120"
      ],
      "fuel": "GASOLINE",
      "cc": 1998,
      "cyl": 4,
      "bore_mm": 86,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-73010"
      ]
    },
  "3ZR":   {
      "display_name": "Toyota 3ZR-FE",
      "image": "/teikin-catalog/3zr.png",
      "teikin_pistons": [
        "46384"
      ],
      "fuel": "GASOLINE",
      "cc": 1986,
      "cyl": 4,
      "bore_mm": 80.5,
      "pin_diameter_mm": 20.012,
      "oem_piston": [
        "13101-37090"
      ]
    },
  "3ZZ":   {
      "display_name": "Toyota 3ZZ-FE",
      "image": "/teikin-catalog/3zz.png",
      "teikin_pistons": [
        "46367"
      ],
      "fuel": "GASOLINE",
      "cc": 1598,
      "cyl": 4,
      "bore_mm": 79,
      "pin_diameter_mm": 20.012,
      "oem_piston": [
        "13101-0D071",
        "13101-0D070",
        "13101-0D111"
      ]
    },
  "4A 8V":   {
      "display_name": "Toyota 4A",
      "image": "/teikin-catalog/4a-8v.png",
      "teikin_pistons": [
        "46336"
      ],
      "fuel": "GASOLINE",
      "cc": 1587,
      "cyl": 4,
      "bore_mm": 81,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-16050"
      ]
    },
  "4AF":   {
      "display_name": "Toyota 4AFE, 4AG",
      "image": "/teikin-catalog/4af.png",
      "teikin_pistons": [
        "46262"
      ],
      "fuel": "GASOLINE",
      "cc": 1587,
      "cyl": 4,
      "bore_mm": 81,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "13101-16160",
        "13101-16201"
      ]
    },
  "4AFE":   {
      "display_name": "Toyota 4AFE, 4AG",
      "image": "/teikin-catalog/4afe.png",
      "teikin_pistons": [
        "46262"
      ],
      "fuel": "GASOLINE",
      "cc": 1587,
      "cyl": 4,
      "bore_mm": 81,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "13101-16160",
        "13101-16201"
      ]
    },
  "4E":   {
      "display_name": "Toyota 4E-FE-II",
      "image": "/teikin-catalog/4e.png",
      "teikin_pistons": [
        "46346"
      ],
      "fuel": "GASOLINE",
      "cc": 1331,
      "cyl": 4,
      "bore_mm": 74,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-11101"
      ]
    },
  "4S":   {
      "display_name": "Toyota 4SFI",
      "image": "/teikin-catalog/4s.png",
      "teikin_pistons": [
        "46289"
      ],
      "fuel": "GASOLINE",
      "cc": 1838,
      "cyl": 4,
      "bore_mm": 82.5,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "13101-74071",
        "13103-74071",
        "13104-74071"
      ]
    },
  "4S II":   {
      "display_name": "Toyota 4SFI",
      "image": "/teikin-catalog/4s-ii.png",
      "teikin_pistons": [
        "46289"
      ],
      "fuel": "GASOLINE",
      "cc": 1838,
      "cyl": 4,
      "bore_mm": 82.5,
      "pin_diameter_mm": 20,
      "oem_piston": [
        "13101-74071",
        "13103-74071",
        "13104-74071"
      ]
    },
  "4ZZ":   {
      "display_name": "Toyota 4ZZFE",
      "image": "/teikin-catalog/4zz.png",
      "teikin_pistons": [
        "46342"
      ],
      "fuel": "GASOLINE",
      "cc": 1398,
      "cyl": 4,
      "bore_mm": 79,
      "pin_diameter_mm": 20.012,
      "oem_piston": [
        "13101-22071",
        "13101-22051"
      ]
    },
  "5A":   {
      "display_name": "Toyota 5AF",
      "image": "/teikin-catalog/5a.png",
      "teikin_pistons": [
        "46290"
      ],
      "fuel": "GASOLINE",
      "cc": 1498,
      "cyl": 4,
      "bore_mm": 78.7,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-15040"
      ]
    },
  "5E":   {
      "display_name": "Toyota 5E-FE",
      "image": "/teikin-catalog/5e.png",
      "teikin_pistons": [
        "46258"
      ],
      "fuel": "GASOLINE",
      "cc": 1497,
      "cyl": 4,
      "bore_mm": 74,
      "pin_diameter_mm": 18,
      "oem_piston": [
        "13101-11131",
        "13101-11161"
      ]
    },
  "5L":   {
      "display_name": "Toyota 5L",
      "image": "/teikin-catalog/5l.png",
      "teikin_pistons": [
        "46273",
        "46273A",
        "46273AG",
        "46273G"
      ],
      "fuel": "DIESEL",
      "cc": 2986,
      "cyl": 4,
      "bore_mm": 99.5,
      "pin_diameter_mm": 29,
      "oem_piston": [
        "13101-54120"
      ]
    },
  "5S 10":   {
      "display_name": "Toyota 5SFE",
      "image": "/teikin-catalog/5s-10.png",
      "teikin_pistons": [
        "46279"
      ],
      "fuel": "GASOLINE",
      "cc": 2164,
      "cyl": 4,
      "bore_mm": 87,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-74130",
        "13101-74080"
      ]
    },
  "5S 20":   {
      "display_name": "Toyota 5SFE",
      "image": "/teikin-catalog/5s-20.png",
      "teikin_pistons": [
        "46279"
      ],
      "fuel": "GASOLINE",
      "cc": 2164,
      "cyl": 4,
      "bore_mm": 87,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-74130",
        "13101-74080"
      ]
    },
  "5VZ":   {
      "display_name": "Toyota 5VZ-FE",
      "image": "/teikin-catalog/5vz.png",
      "teikin_pistons": [
        "46666"
      ],
      "fuel": "GASOLINE",
      "cc": 3378,
      "cyl": 6,
      "bore_mm": 93.5,
      "pin_diameter_mm": 22,
      "oem_piston": [
        "13101-62060"
      ]
    },
};
