/**
 * Reads tmp/otoba/<engine_code>/fitment_rows.json files and emits ONE
 * SQL promotion file that, when run manually in Supabase SQL Editor:
 *
 *   1. Sanity-checks that data_sources.otoba_ru exists.
 *   2. Builds a TEMP work table of all parsed rows across all engines.
 *   3. INSERTs missing vehicle_models                 (ON CONFLICT DO NOTHING)
 *   4. Resolves vehicle_model_id + existing_fitment_id per row
 *   5. UPDATEs MATCHED engine_fitments               (confidence=0.90,
 *      notes='verified from otoba.ru', source_id=otoba_ru, years)
 *   6. INSERTs OTOBA_ONLY engine_fitments             (ON CONFLICT DO NOTHING)
 *   7. UPSERTs data_source_links for every parsed row
 *
 * Does NOT delete master-only fitments. Does NOT touch engines,
 * products, parts, stock.
 *
 * Output file:
 *   supabase/promotions/generated/otoba_promote_fitments.sql
 *
 * Run:
 *   npx tsx scripts/import/generate_otoba_promotion_sql.ts
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import process from 'node:process';

type StagingRow = {
  row_number: number;
  source_url: string;
  raw_text: string;
  raw_json: Record<string, unknown>;
  normalized_json: {
    engine_code: string;
    engine_alias: string;
    vehicle_make: string;
    vehicle_model: string;
    generation: string | null;
    chassis_code: string | null;
    year_from: number | null;
    year_to: number | null;
    entity_key: string;
  };
  engine_code: string;
  vehicle_make: string;
  vehicle_model: string;
  confidence: number;
};

type EnginePayload = {
  engine: { brand: string; engine_code: string; engine_alias: string; url: string };
  rows: StagingRow[];
};

function sql(v: string): string { return `'${v.replace(/'/g, "''")}'`; }
function sqlOrNull(v: string | null | undefined): string {
  return v === null || v === undefined ? 'NULL' : sql(v);
}
function intOrNull(v: number | null | undefined): string {
  return v === null || v === undefined ? 'NULL' : String(v);
}
function sqlJson(v: unknown): string { return `${sql(JSON.stringify(v))}::jsonb`; }

async function main() {
  const projectRoot = resolve(__dirname, '..', '..');
  const otobaRoot = resolve(projectRoot, 'tmp', 'otoba');
  const outPath = resolve(projectRoot, 'supabase', 'promotions', 'generated', 'otoba_promote_fitments.sql');

  let entries: string[];
  try { entries = await readdir(otobaRoot); } catch {
    throw new Error(`No parser output at ${otobaRoot}. Run otoba_fitment_batch_parser.ts first.`);
  }

  const payloads: EnginePayload[] = [];
  for (const e of entries) {
    if (e === 'index.json') continue;
    const fp = resolve(otobaRoot, e, 'fitment_rows.json');
    try {
      const raw = await readFile(fp, 'utf8');
      const json = JSON.parse(raw) as EnginePayload;
      if (json?.rows?.length) payloads.push(json);
    } catch { /* skip */ }
  }
  if (payloads.length === 0) throw new Error('No engine payloads with rows');

  // Flatten all rows into a single list with engine context.
  type FlatRow = StagingRow & { brand: string };
  const flat: FlatRow[] = [];
  for (const p of payloads) {
    for (const r of p.rows) flat.push({ ...r, brand: p.engine.brand });
  }
  const engineCodes = Array.from(new Set(flat.map((r) => r.engine_code))).sort();

  const L: string[] = [];

  L.push('-- =====================================================================');
  L.push('-- AUTO-GENERATED by scripts/import/generate_otoba_promotion_sql.ts');
  L.push(`-- Generated at: ${new Date().toISOString()}`);
  L.push(`-- Engines: ${payloads.length} | total rows: ${flat.length}`);
  L.push('--');
  L.push('-- WRITES ONLY:');
  L.push('--   * public.vehicle_models       (INSERT, ON CONFLICT DO NOTHING)');
  L.push('--   * public.engine_fitments      (UPDATE matched, INSERT new)');
  L.push('--   * public.data_source_links    (UPSERT per row)');
  L.push('-- DOES NOT touch engines, products, part_*, stock_items,');
  L.push('-- brands, part_categories, sales_channels, media_*, ');
  L.push('-- catalog_import_*.');
  L.push('-- master-only fitments are LEFT INTACT.');
  L.push('-- =====================================================================');
  L.push('');
  L.push('BEGIN;');
  L.push('');

  // -------------------------------------------------------------------
  // 0) Sanity: otoba_ru must exist
  // -------------------------------------------------------------------
  L.push('DO $$');
  L.push('DECLARE v_id bigint;');
  L.push('BEGIN');
  L.push(`  SELECT id INTO v_id FROM public.data_sources WHERE code = 'otoba_ru';`);
  L.push('  IF v_id IS NULL THEN');
  L.push(`    RAISE EXCEPTION 'data_source "otoba_ru" missing — apply Stage A seed first.';`);
  L.push('  END IF;');
  L.push('END $$;');
  L.push('');

  // -------------------------------------------------------------------
  // 1) TEMP table with all parsed rows across all engines
  // -------------------------------------------------------------------
  L.push('-- ----------------------------------------------------------------');
  L.push('-- 1) Build the per-row work-set in a TEMP table.');
  L.push('-- ----------------------------------------------------------------');
  L.push('CREATE TEMP TABLE tmp_promo_rows ON COMMIT DROP AS');
  L.push('SELECT * FROM (VALUES');
  flat.forEach((r, idx) => {
    const nj = r.normalized_json;
    const parts = [
      sql(r.engine_code),
      sql(r.brand.toLowerCase()), // make_code
      sql(r.brand),                // brand label (== vehicle_make)
      sql(r.vehicle_model),
      sqlOrNull(nj.generation),
      sqlOrNull(nj.chassis_code),
      intOrNull(nj.year_from),
      intOrNull(nj.year_to),
      sql(r.source_url),
      sql(r.raw_text),
      sqlJson(r.raw_json),
      sqlJson(nj),
      sql(nj.entity_key),
    ];
    const suffix = idx === flat.length - 1 ? '' : ',';
    L.push(`  (${parts.join(', ')})${suffix}`);
  });
  L.push(') AS v(');
  L.push('  engine_code, make_code, vehicle_make, vehicle_model,');
  L.push('  generation, chassis_code, year_from, year_to,');
  L.push('  source_url, raw_text, raw_json, normalized_json, entity_key');
  L.push(');');
  L.push('');
  L.push('ALTER TABLE tmp_promo_rows ADD COLUMN vehicle_model_id    bigint;');
  L.push('ALTER TABLE tmp_promo_rows ADD COLUMN existing_fitment_id bigint;');
  L.push('');

  // -------------------------------------------------------------------
  // 2) Ensure vehicle_make for any brand we mention
  //    (no-op if seed already covered it; idempotent)
  // -------------------------------------------------------------------
  L.push('-- ----------------------------------------------------------------');
  L.push('-- 2) Ensure vehicle_makes exist for every brand seen.');
  L.push('-- ----------------------------------------------------------------');
  const brandsSeen = Array.from(new Set(flat.map((r) => r.brand)));
  for (const b of brandsSeen) {
    L.push(`INSERT INTO public.vehicle_makes (code, name) VALUES (${sql(b.toLowerCase())}, ${sql(b)}) ON CONFLICT (code) DO NOTHING;`);
  }
  L.push('');

  // -------------------------------------------------------------------
  // 3) Insert missing vehicle_models
  // -------------------------------------------------------------------
  L.push('-- ----------------------------------------------------------------');
  L.push('-- 3) Insert missing vehicle_models (ON CONFLICT DO NOTHING).');
  L.push('-- ----------------------------------------------------------------');
  L.push('INSERT INTO public.vehicle_models');
  L.push('  (make_code, model_name, generation, chassis_code, year_from, year_to, notes)');
  L.push('SELECT DISTINCT');
  L.push('  p.make_code, p.vehicle_model, p.generation, p.chassis_code,');
  L.push('  p.year_from, p.year_to, ' + sql('verified from otoba.ru'));
  L.push('FROM tmp_promo_rows p');
  L.push('ON CONFLICT DO NOTHING;');
  L.push('');

  // -------------------------------------------------------------------
  // 4) Resolve vehicle_model_id + existing_fitment_id
  // -------------------------------------------------------------------
  L.push('-- ----------------------------------------------------------------');
  L.push('-- 4) Resolve vehicle_model_id and existing engine_fitment id.');
  L.push('-- ----------------------------------------------------------------');
  L.push('UPDATE tmp_promo_rows p');
  L.push('SET vehicle_model_id = vm.id');
  L.push('FROM public.vehicle_models vm');
  L.push('WHERE vm.make_code = p.make_code');
  L.push('  AND lower(trim(vm.model_name)) = lower(trim(p.vehicle_model))');
  L.push("  AND coalesce(vm.generation,   '') = coalesce(p.generation,   '')");
  L.push("  AND coalesce(vm.chassis_code, '') = coalesce(p.chassis_code, '');");
  L.push('');
  L.push('UPDATE tmp_promo_rows p');
  L.push('SET existing_fitment_id = ef.id');
  L.push('FROM public.engine_fitments ef');
  L.push('WHERE ef.engine_code = p.engine_code');
  L.push('  AND ef.vehicle_model_id = p.vehicle_model_id;');
  L.push('');

  // -------------------------------------------------------------------
  // 5) UPDATE matched fitments
  // -------------------------------------------------------------------
  L.push('-- ----------------------------------------------------------------');
  L.push('-- 5) MATCHED: UPDATE existing engine_fitments in place.');
  L.push('-- ----------------------------------------------------------------');
  L.push('UPDATE public.engine_fitments ef');
  L.push('SET year_from  = p.year_from,');
  L.push('    year_to    = p.year_to,');
  L.push('    confidence = 0.90,');
  L.push("    notes      = 'verified from otoba.ru',");
  L.push("    source_id  = (SELECT id FROM public.data_sources WHERE code = 'otoba_ru'),");
  L.push('    is_active  = true');
  L.push('FROM tmp_promo_rows p');
  L.push('WHERE ef.id = p.existing_fitment_id');
  L.push('  AND p.existing_fitment_id IS NOT NULL;');
  L.push('');

  // -------------------------------------------------------------------
  // 6) INSERT new fitments for OTOBA_ONLY rows
  // -------------------------------------------------------------------
  L.push('-- ----------------------------------------------------------------');
  L.push('-- 6) OTOBA_ONLY: INSERT new engine_fitments.');
  L.push('-- ----------------------------------------------------------------');
  L.push('INSERT INTO public.engine_fitments');
  L.push('  (engine_code, vehicle_model_id, year_from, year_to,');
  L.push('   source_id, confidence, notes, is_active)');
  L.push('SELECT');
  L.push('  p.engine_code, p.vehicle_model_id, p.year_from, p.year_to,');
  L.push(`  (SELECT id FROM public.data_sources WHERE code = 'otoba_ru'),`);
  L.push("  0.90, 'verified from otoba.ru', true");
  L.push('FROM tmp_promo_rows p');
  L.push('WHERE p.existing_fitment_id IS NULL');
  L.push('  AND p.vehicle_model_id IS NOT NULL');
  L.push('ON CONFLICT DO NOTHING;');
  L.push('');

  // -------------------------------------------------------------------
  // 7) UPSERT data_source_links
  // -------------------------------------------------------------------
  L.push('-- ----------------------------------------------------------------');
  L.push('-- 7) UPSERT data_source_links for every parsed row.');
  L.push('-- ----------------------------------------------------------------');
  L.push('INSERT INTO public.data_source_links');
  L.push('  (source_id, source_run_id, entity_type, entity_key,');
  L.push('   source_page, source_url, raw_text, raw_json, confidence)');
  L.push('SELECT');
  L.push(`  (SELECT id FROM public.data_sources WHERE code = 'otoba_ru'),`);
  L.push("  NULL, 'engine_fitment', p.entity_key, NULL, p.source_url, p.raw_text, p.raw_json, 0.90");
  L.push('FROM tmp_promo_rows p');
  L.push('ON CONFLICT (source_id, COALESCE(source_run_id, 0), entity_type, entity_key,');
  L.push("            COALESCE(source_page, ''), COALESCE(source_url, ''))");
  L.push('DO UPDATE SET');
  L.push('  raw_text   = EXCLUDED.raw_text,');
  L.push('  raw_json   = EXCLUDED.raw_json,');
  L.push('  confidence = EXCLUDED.confidence,');
  L.push('  source_url = EXCLUDED.source_url;');
  L.push('');

  L.push('COMMIT;');
  L.push('');

  // -------------------------------------------------------------------
  // Verification
  // -------------------------------------------------------------------
  L.push('-- =====================================================================');
  L.push('-- Verification per engine_code (read-only).');
  L.push('-- =====================================================================');
  L.push('SELECT ef.engine_code,');
  L.push('       COUNT(*)                                              AS fitments_total,');
  L.push("       COUNT(*) FILTER (WHERE ef.confidence = 0.90)          AS verified_otoba,");
  L.push("       COUNT(*) FILTER (WHERE ef.confidence < 0.90)          AS needs_verification");
  L.push('FROM public.engine_fitments ef');
  L.push(`WHERE ef.engine_code IN (${engineCodes.map(sql).join(', ')})`);
  L.push('GROUP BY ef.engine_code');
  L.push('ORDER BY ef.engine_code;');
  L.push('');
  L.push('SELECT ef.engine_code, vm.model_name, vm.generation, vm.chassis_code,');
  L.push('       ef.year_from, ef.year_to, ef.confidence, ds.code AS source_code, ef.notes');
  L.push('FROM public.engine_fitments ef');
  L.push('JOIN public.vehicle_models vm  ON vm.id = ef.vehicle_model_id');
  L.push('LEFT JOIN public.data_sources ds ON ds.id = ef.source_id');
  L.push(`WHERE ef.engine_code IN (${engineCodes.map(sql).join(', ')})`);
  L.push('ORDER BY ef.engine_code, vm.model_name, vm.generation NULLS LAST;');
  L.push('');
  L.push('SELECT ds.code AS source_code, l.entity_key, l.confidence');
  L.push('FROM public.data_source_links l');
  L.push('JOIN public.data_sources ds ON ds.id = l.source_id');
  L.push(`WHERE ds.code = 'otoba_ru'`);
  L.push(`  AND (${engineCodes.map((ec) => `l.entity_key LIKE ${sql(ec + ':%')}`).join(' OR ')})`);
  L.push('ORDER BY l.entity_key;');
  L.push('');

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, L.join('\n'), 'utf8');
  process.stderr.write(`Wrote ${outPath}\n`);
  process.stderr.write(`Engines: ${payloads.length} | rows: ${flat.length}\nNo SQL executed.\n`);
}

main().catch((err) => { console.error(err); process.exit(1); });
