/**
 * Reads tmp/otoba/<engine_code>/fitment_rows.json files (output of
 * otoba_fitment_batch_parser.ts) and emits ONE SQL file that, when
 * run manually in Supabase SQL Editor, will:
 *
 *   1. Ensure data_sources.code='otoba_ru' exists (defensive UPSERT).
 *   2. For each engine_code, create / reuse a catalog_import_batches
 *      row with batch_code '<engine_lower>_otoba_fitment_<YYYYMMDD>'.
 *   3. UPSERT N catalog_import_rows per batch
 *      (ON CONFLICT (batch_id, row_number) DO UPDATE).
 *
 * Writes only:
 *   public.data_sources
 *   public.catalog_import_batches
 *   public.catalog_import_rows
 *
 * Output file:
 *   supabase/imports/generated/otoba_staging_import.sql
 *
 * Run:
 *   npx tsx scripts/import/generate_otoba_staging_sql.ts
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import process from 'node:process';

type StagingRow = {
  row_number: number;
  source_url: string;
  raw_text: string;
  raw_json: Record<string, unknown>;
  normalized_json: Record<string, unknown>;
  engine_code: string;
  vehicle_make: string;
  vehicle_model: string;
  confidence: number;
  status: string;
};

type EnginePayload = {
  engine: { brand: string; engine_code: string; engine_alias: string; url: string };
  engine_metadata: unknown;
  rows: StagingRow[];
};

// Postgres string literal escape (single quotes).
function sql(v: string): string {
  return `'${v.replace(/'/g, "''")}'`;
}

function sqlJson(v: unknown): string {
  return `${sql(JSON.stringify(v))}::jsonb`;
}

function todayCompact(): string {
  const d = new Date();
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, '0');
  const dd = String(d.getUTCDate()).padStart(2, '0');
  return `${yyyy}${mm}${dd}`;
}

async function main() {
  const projectRoot = resolve(__dirname, '..', '..');
  const otobaRoot = resolve(projectRoot, 'tmp', 'otoba');
  const outPath = resolve(projectRoot, 'supabase', 'imports', 'generated', 'otoba_staging_import.sql');

  let entries: string[];
  try {
    entries = await readdir(otobaRoot);
  } catch {
    throw new Error(`No parser output at ${otobaRoot}. Run otoba_fitment_batch_parser.ts first.`);
  }

  const payloads: EnginePayload[] = [];
  for (const e of entries) {
    if (e === 'index.json') continue;
    const fp = resolve(otobaRoot, e, 'fitment_rows.json');
    try {
      const raw = await readFile(fp, 'utf8');
      const json = JSON.parse(raw) as EnginePayload;
      if (json?.rows?.length) payloads.push(json);
    } catch {
      // skip — engine had error or no rows
    }
  }

  if (payloads.length === 0) {
    throw new Error('No engine payloads with rows found in tmp/otoba/*/fitment_rows.json');
  }

  const stamp = todayCompact();
  const lines: string[] = [];

  lines.push('-- =====================================================================');
  lines.push('-- AUTO-GENERATED by scripts/import/generate_otoba_staging_sql.ts');
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push(`-- Engines: ${payloads.length} | total rows: ${payloads.reduce((a, p) => a + p.rows.length, 0)}`);
  lines.push('--');
  lines.push('-- WRITES ONLY: data_sources, catalog_import_batches, catalog_import_rows.');
  lines.push('-- DOES NOT touch master tables (engines, vehicle_models, engine_fitments,');
  lines.push('-- products, part_*, stock_items, brands, part_categories, …).');
  lines.push('-- =====================================================================');
  lines.push('');
  lines.push('BEGIN;');
  lines.push('');

  // 1) Defensive UPSERT of otoba_ru
  lines.push('-- 1) Ensure otoba_ru data_source exists (idempotent).');
  lines.push(`INSERT INTO public.data_sources (code, name, source_type, url, language, notes)`);
  lines.push(`VALUES ('otoba_ru', 'Otoba.ru vehicle fitment source', 'website', 'https://otoba.ru', 'ru', 'Source for engine-to-vehicle fitment verification')`);
  lines.push('ON CONFLICT (code) DO NOTHING;');
  lines.push('');

  for (const p of payloads) {
    const batchCode = `${p.engine.engine_code.toLowerCase()}_otoba_fitment_${stamp}`;
    const headerNote = `Otoba batch for ${p.engine.brand} ${p.engine.engine_alias} (${p.engine.url})`;

    lines.push('-- =================================================================');
    lines.push(`-- ${p.engine.brand} ${p.engine.engine_code} (${p.engine.engine_alias}) — ${p.rows.length} row(s)`);
    lines.push('-- =================================================================');

    // 2) Create / reuse batch
    lines.push(`INSERT INTO public.catalog_import_batches`);
    lines.push(`  (source_id, batch_code, import_type, status, source_url, parser_name, parser_version, notes, meta_json)`);
    lines.push(`SELECT id, ${sql(batchCode)}, 'otoba_fitment', 'normalized', ${sql(p.engine.url)},`);
    lines.push(`       'otoba_fitment_batch_parser', 'v1', ${sql(headerNote)},`);
    lines.push(`       jsonb_build_object('engine_code', ${sql(p.engine.engine_code)}, 'engine_alias', ${sql(p.engine.engine_alias)}, 'brand', ${sql(p.engine.brand)})`);
    lines.push(`FROM public.data_sources WHERE code = 'otoba_ru'`);
    lines.push(`ON CONFLICT (batch_code) DO UPDATE SET`);
    lines.push(`  source_url = EXCLUDED.source_url,`);
    lines.push(`  notes      = EXCLUDED.notes,`);
    lines.push(`  meta_json  = EXCLUDED.meta_json,`);
    lines.push(`  status     = 'normalized';`);
    lines.push('');

    // 3) UPSERT rows
    lines.push(`WITH b AS (SELECT id AS batch_id FROM public.catalog_import_batches WHERE batch_code = ${sql(batchCode)}),`);
    lines.push(`src(row_number, source_url, raw_text, raw_json, normalized_json,`);
    lines.push(`    detected_entity_type, engine_code, category_code, part_number,`);
    lines.push(`    brand_name, vehicle_make, vehicle_model, confidence, status) AS (`);
    lines.push(`  VALUES`);
    const valueLines = p.rows.map((r, idx) => {
      const parts = [
        `${r.row_number}::int`,
        sql(r.source_url),
        sql(r.raw_text),
        sqlJson(r.raw_json),
        sqlJson(r.normalized_json),
        sql('engine_fitment'),
        sql(r.engine_code),
        'NULL::text',
        'NULL::text',
        'NULL::text',
        sql(r.vehicle_make),
        sql(r.vehicle_model),
        `${r.confidence}::numeric(3,2)`,
        sql(r.status),
      ];
      const suffix = idx === p.rows.length - 1 ? '' : ',';
      return `    (${parts.join(', ')})${suffix}`;
    });
    lines.push(...valueLines);
    lines.push(`)`);
    lines.push(`INSERT INTO public.catalog_import_rows (`);
    lines.push(`  batch_id, row_number, source_url, raw_text, raw_json, normalized_json,`);
    lines.push(`  detected_entity_type, engine_code, category_code, part_number,`);
    lines.push(`  brand_name, vehicle_make, vehicle_model, confidence, status`);
    lines.push(`)`);
    lines.push(`SELECT b.batch_id, s.row_number, s.source_url, s.raw_text, s.raw_json, s.normalized_json,`);
    lines.push(`       s.detected_entity_type, s.engine_code, s.category_code, s.part_number,`);
    lines.push(`       s.brand_name, s.vehicle_make, s.vehicle_model, s.confidence, s.status`);
    lines.push(`FROM src s CROSS JOIN b`);
    lines.push(`ON CONFLICT (batch_id, row_number) DO UPDATE SET`);
    lines.push(`  source_url           = EXCLUDED.source_url,`);
    lines.push(`  raw_text             = EXCLUDED.raw_text,`);
    lines.push(`  raw_json             = EXCLUDED.raw_json,`);
    lines.push(`  normalized_json      = EXCLUDED.normalized_json,`);
    lines.push(`  detected_entity_type = EXCLUDED.detected_entity_type,`);
    lines.push(`  engine_code          = EXCLUDED.engine_code,`);
    lines.push(`  vehicle_make         = EXCLUDED.vehicle_make,`);
    lines.push(`  vehicle_model        = EXCLUDED.vehicle_model,`);
    lines.push(`  confidence           = EXCLUDED.confidence,`);
    lines.push(`  status               = EXCLUDED.status,`);
    lines.push(`  error_text           = NULL;`);
    lines.push('');
  }

  lines.push('COMMIT;');
  lines.push('');
  lines.push('-- =====================================================================');
  lines.push('-- Summary (read-only). Run after the COMMIT above.');
  lines.push('-- =====================================================================');
  lines.push(`SELECT b.batch_code, b.status, b.import_type, b.rows_total, COUNT(r.id) AS rows_in_batch`);
  lines.push(`FROM public.catalog_import_batches b`);
  lines.push(`LEFT JOIN public.catalog_import_rows r ON r.batch_id = b.id`);
  lines.push(`WHERE b.batch_code IN (`);
  payloads.forEach((p, idx) => {
    const bc = `${p.engine.engine_code.toLowerCase()}_otoba_fitment_${stamp}`;
    lines.push(`  ${sql(bc)}${idx === payloads.length - 1 ? '' : ','}`);
  });
  lines.push(`)`);
  lines.push(`GROUP BY b.batch_code, b.status, b.import_type, b.rows_total`);
  lines.push(`ORDER BY b.batch_code;`);
  lines.push('');

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, lines.join('\n'), 'utf8');
  process.stderr.write(`Wrote ${outPath}\n`);
  process.stderr.write(`Engines: ${payloads.length} | rows: ${payloads.reduce((a, p) => a + p.rows.length, 0)}\n`);
  process.stderr.write(`No SQL executed.\n`);
}

main().catch((err) => { console.error(err); process.exit(1); });
